"""Writes server/seed.sql: the answer schedule (same day order as index.html) and the valid-guess list.

Ports the page's mulberry32 + Fisher-Yates shuffle exactly, so puzzle No. N is
the same word in the browser-only modes and on the server.
Usage: python3 make_seed.py answers_sorted.txt extra_valid.txt ../server/seed.sql
"""
import sys

M = 0xFFFFFFFF

def mulberry32(a):
    a &= M
    def r():
        nonlocal a
        a = (a + 0x6D2B79F5) & M
        t = ((a ^ (a >> 15)) * (1 | a)) & M
        t = ((t + (((t ^ (t >> 7)) * (61 | t)) & M)) & M) ^ t
        return ((t ^ (t >> 14)) & M) / 4294967296
    return r

answers_path, valid_path, out_path = sys.argv[1:4]
answers = open(answers_path).read().split()
extra = open(valid_path).read().split()

rng = mulberry32(20260928)
order = list(range(len(answers)))
for i in range(len(order) - 1, 0, -1):
    j = int(rng() * (i + 1))
    order[i], order[j] = order[j], order[i]

with open(out_path, "w") as f:
    f.write("-- Generated by tools/build_words.sh. Do not edit by hand.\n")
    f.write("BEGIN;\nTRUNCATE answers;\nTRUNCATE valid_words;\n")
    f.write("INSERT INTO answers (day_index, word) VALUES\n")
    f.write(",\n".join(f"({d},'{answers[i]}')" for d, i in enumerate(order)) + ";\n")
    words = sorted(set(answers) | set(extra))
    for k in range(0, len(words), 1000):
        chunk = words[k:k + 1000]
        f.write("INSERT INTO valid_words (word) VALUES " + ",".join(f"('{w}')" for w in chunk) + ";\n")
    f.write("COMMIT;\n")
print(f"seed: {len(answers)} answers, {len(set(answers) | set(extra))} valid words; day 0 = {answers[order[0]]}, day 5 = {answers[order[5]]}")
